import Head from "next/head";
import Image from "next/image";
import "antd/dist/antd.css";
import styles from "../styles/Home.module.css";
import React from "react";
import Chat from "../components/chat/Message";
import History from "../components/chat/History";
import CreateRoom from "../components/chat/CreateRoom";
// import NewMessage from "./MessageInput";

import {PlusOutlined, SearchOutlined, BellFilled, MenuOutlined, 
        LogoutOutlined, SettingOutlined,
        MenuUnfoldOutlined, MenuFoldOutlined ,  
        PieChartOutlined, DesktopOutlined, ContainerOutlined,
        MailOutlined, AppstoreOutlined, HeartTwoTone,  } from '@ant-design/icons';

import {Layout, Button, Menu, Row, Col, AutoComplete} from 'antd';

const { Header, Footer, Sider, Content } =Layout;

function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}
//menu
const items = [
  getItem('Цэс', '1', <PieChartOutlined 
  style={{
    fontSize:18,
   

  }}
  />),
  getItem('Чатбот', '2', <DesktopOutlined  style={{
    fontSize:18,
   

  }} />),
  getItem('Төлбөр', '3', <ContainerOutlined  style={{
    fontSize:18,


  }} />),
  getItem('Nav', 'sub1', <MailOutlined  style={{
    fontSize:18,
  

  }} />, [
    getItem( '5'),
    getItem('6'),
    getItem('7'),
    getItem('8'),
  ]),
  getItem('Nav', 'sub2', <AppstoreOutlined  style={{
    fontSize:18,
  

  }}/>, [
    getItem('9'),
    getItem( '10'),
    getItem('Submenu', 'sub3', null, [getItem('Option 11', '11'), getItem('Option 12', '12')]),
  ]),

  getItem('Гарах', '4',<LogoutOutlined style={{
    fontSize:18,


  }} />),
  getItem('Тохиргоо', '5',<SettingOutlined style={{
    fontSize:18,
    marginTop:10,
  }} />),
];
//

// export default function Home() {
  const App = () => {

  const [collapsed, setCollapsed] = React.useState(false);

  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };

  return (
    <Layout>
      <Sider  width = {150} className = {styles.side}>
        <div
      style={{
        width: 25,
      }}
      ></div>
      <Button
        type="primary"
        onClick={toggleCollapsed}
        style={{
          width:80,
          height:60,
          fontSize:24,
          marginBottom: 16,
      
        }}
      >
        {collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
      </Button>

      <Menu
        defaultSelectedKeys={['1']}
        defaultOpenKeys={['sub1']}
        mode="inline"
        theme="light"
        color="green"
        inlineCollapsed={collapsed}
        items={items}
      />
      
      </Sider>
     
      <Layout>
        <Header className = {styles.head}> 
        <Button className = {styles.btn} icon={<SearchOutlined />}>Хэрэглэгч хайх </Button>
      {/* <div className={styles.noti}>
        <Image
          alt="Monosolution is logo"
          src="/bell.svg"
          width={100}
          height={24}
        />
      </div> */}
      <BellFilled className={styles.bell}/>
      

        </Header>
        <Layout>
          <Sider width = {400} className = {styles.side2}>
            <Row>
              <Col> 
              <h1> Миний Чатны Түүх </h1>
              </Col>
              <Col>
              <CreateRoom/>
              

              </Col>

            </Row>
            <Row>
              <History/>
            </Row>
            
          {/* <button  className= {styles.btn} type="submit"> 
           Бүлэг үүсгэх <PlusOutlined/>                               
          </button> */}
           </Sider>
        <Layout>
        <Content height= {200} className = {styles.content}>
        {/* <button  className= {styles.btn} type="submit">
          Хэрэглэгч хайх                               
      </button> */}
       <Chat/>
         {/* <input placeholder= "Message" className= {styles.message}> </input> */}

        </Content>
        {/* <Footer className = {styles.footer}> Made <HeartTwoTone twoToneColor="#eb2f96" />  by Bayartsetseg

        </Footer> */}
        </Layout>
        </Layout>
        
        
      </Layout>
    </Layout>
  //   <div className={styles.container}>
  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Chat &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>ChatBot&rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/canary/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
   );
};
export default App;