import Head from "next/head";
import Image from "next/image";
import "antd/dist/antd.css";
import styles from "../styles/Home.module.css";
import React from "react";

import {PlusOutlined, SearchOutlined, BellOutlined, MenuOutlined,
        MenuUnfoldOutlined, MenuFoldOutlined ,  
        PieChartOutlined, DesktopOutlined, ContainerOutlined,
        MailOutlined, AppstoreOutlined  } from '@ant-design/icons';

import {Layout, Button, Menu, AutoComplete} from 'antd';

const { Header, Footer, Sider, Content } =Layout;

function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}
//menu
const items = [
  getItem( <PieChartOutlined />),
  getItem(<DesktopOutlined />),
  getItem(<ContainerOutlined />),
  getItem('Nav', 'sub1', <MailOutlined />, [
    getItem( '5'),
    getItem('6'),
    getItem('7'),
    getItem('8'),
  ]),
  getItem('Nav', 'sub2', <AppstoreOutlined />, [
    getItem('9'),
    getItem( '10'),
    getItem('Submenu', 'sub3', null, [getItem('Option 11', '11'), getItem('Option 12', '12')]),
  ]),
];
//

// export default function Home() {
  const App = () => {

  const [collapsed, setCollapsed] = React.useState(false);

  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };

  return (
    <Layout>
      <Sider  width = {80} className = {styles.side}>
      <Button
        type="primary"
        onClick={toggleCollapsed}
        style={{
          width:80,
          height:60,
          marginBottom: 16,
      
        }}
      >
        {collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
      </Button>

      <Menu
        defaultSelectedKeys={['1']}
        defaultOpenKeys={['sub1']}
        mode="inline"
        theme="light"
        color="green"
        inlineCollapsed={collapsed}
        items={items}
      />
      
      </Sider>
     
      <Layout>
        <Header className = {styles.head}> 
        <Button className = {styles.btn} icon={<SearchOutlined />}>Хэрэглэгч хайх </Button>

      <p className={styles.text}> <PlusOutlined/> Chat - Connection </p>
      <div className={styles.noti}>
        <Image
          alt="Monosolution is logo"
          src="/bell.svg"
          width={100}
          height={24}
        />
      </div>
      

        </Header>
        <Layout>
          <Sider width = {500} className = {styles.side2}>
          
        </Sider>
        <Content height= {200} className = {styles.content}>
        <button  className= {styles.btn} type="submit">
          Хэрэглэгч хайх                               
      </button>
        </Content>
        
        </Layout>
        
        <Footer className = {styles.footer}>foo

        </Footer>
      </Layout>
    </Layout>
  //   <div className={styles.container}>
  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Chat &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>ChatBot&rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/canary/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
   );
};
export default App;